"""add unique contrains

Revision ID: a53ca7583e6c
Revises: 0000644d013c
Create Date: 2024-02-05 20:54:52.931033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a53ca7583e6c'
down_revision: Union[str, None] = '0000644d013c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'doctor_opinions', ['record_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctor_opinions', type_='unique')
    # ### end Alembic commands ###
